POST http://localhost:3000/cart
content-type: application/json

{
  "product_id": 3,
  "quantity": 1
}

###

PUT http://localhost:3000/cart/add_item
content-type: application/json

{
  "product_id": 3,
  "quantity": 2
}

###

DELETE  http://localhost:3000/cart/3
content-type: application/json
